# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180327_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='teachers/default', upload_to='teachers/%Y/%m', verbose_name='logo'),
        ),
    ]
