# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-29 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20180328_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, default='\u540e\u7aef\u5f00\u53d1', max_length=200, null=True, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
    ]
