# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-29 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u89c6\u9891\u5730\u5740'),
        ),
    ]
