# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-29 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_video_learn_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_know',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_advice',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u8bb2\u5e08\u5efa\u8bae'),
        ),
    ]
